// Date Format ISO 8601
//:notitle:
//:authors: Norbert Reschke
:subject: Medienkonzept der Ausbildungsvorbereitung am Hans-Sachs-Berufskolleg
:keywords: Hans-Sachs-Berufskolleg, Medienkonzept, Ausbildungsvorbereitung
:numbered:
:sectnumlevels: 5
:toclevels: 5

= Medienkonzept der Ausbildungsvorbereitung am Hans-Sachs-Berufskolleg, Oberhausen

== Sollbedingungen für Lehrerinnen und Lehrer

Lehrerinnen und Lehrer benötigen ein dienstliches Smartphone und einen Laptop und eine datensichere dienstliche Cloudplattform, die dem Stand der Technik entspricht (z.B. iserv).

Lehrerinnen und Lehrer benötigen den Zugriff auf Datenbanken und Online-Fortbildungen zur Einschätzung von Kosten/Nutzen Verhältnis und Einsatzmöglichkeiten der verschiedenen Medien und Plattformen.

== Sollbedingungen für Schülerinnen und Schüler

=== Ausstattung

Schülerinnen und Schüler benötigen Räume innerhalb und außerhalb der Schule, die eine geschützte und geschlossene Lernumgebung mit einem Internetzugang über ein freies Wlan und Lan bieten.

Neben den üblichen Smartphones, die gut geeignet sind für digitale Lernkarteien, Bücher im Epub-Format und Texte im HTML-Format,
E-Mail und Kurznachrichten und Audiodateien oder Telefonate und Videokonferenzen
benötigen Schülerinnen und Schüler Laptops oder Arbeitsplatzrechner, um sinnvoll zumindest mit Textverarbeitung, Tabellenkalkulation und Vektorgrafik arbeiten zu können.

Darüberhinaus benötigen die Schülerinnen und Schüler den Zugang zu Lernplattformen (s.u.).

=== Software
https://de.wikipedia.org/wiki/EPUB[Epub]-Lehrbücher z.B. Englisch: Kickoff Foundation und Upgrade, Klett,
freie, offene oder proprietäre Programme folgender Anwendungen:

[cols="1,1",options="header",width=70%]
|=== 
|Programm|Beispiel
|https://en.wikipedia.org/wiki/Web_browser[Web-Browser]|https://www.mozilla.org/[firefox]
|https://en.wikipedia.org/wiki/Text_editor[Text-Editor]|https://wiki.gnome.org/Apps/Gedit[gedit]
|https://en.wikipedia.org/wiki/Email_client[E-Mail]|https://thunderbird.net[thunderbird]
|https://en.wikipedia.org/wiki/Word_processor[Textverarbeitung]|https://www.libreoffice.org/discover/writer/[
Writer]
|https://en.wikipedia.org/wiki/Spreadsheet[Tabellenkalkulation]|https://www.libreoffice.org/discover/calc/[Calc]
|https://en.wikipedia.org/wiki/Database[Datenbank]|https://www.sqlite.org/index.html[sqlite], https://www.postgresql.org/[postgres]
|https://en.wikipedia.org/wiki/Presentation_program[Präsentationsprogramm]|https://www.libreoffice.org/discover/impress/[Impress]
|https://en.wikipedia.org/wiki/Vector_graphics_editor[Vektorzeichenprogramm] für technische Zeichnungen|https://qcad.org/[qcad]
|https://en.wikipedia.org/wiki/Raster_graphics_editor[Pixelgrafikprogramm]|https://www.gimp.org/[gimp]
|https://en.wikipedia.org/wiki/Desktop_publishing[Layoutprogramm]|https://www.scribus.net/[Scribus]
|https://en.wikipedia.org/wiki/Distributed_version_control[Distributed Revision Control Management]|https://git-scm.com/video/what-is-version-control[git]
|===


 - Beispiel proprietärer Software -> https://products.office.com/de-de/business/office[office365],
 - Beispiel freier Software -> https://getfedora.org/de/workstation/[Fedora-Distribution]

 - Beispiele von Lernplattformen -> https://card2brain.ch/[card2brain], https://www.binogi.de/[binogi], https://www.volkshochschule.de/verbandswelt/service-fuer-volkshochschulen/corona/index.php[VHS-Online]

- Beispiel einer Arbeitsplattform einschließlich Datenaustausch und Sicherung -> https://hans-sachs-bk.schulserver.de/iserv/[iserv]

== Lernziele

- Analyse von Daten hinsichtlich Validität, Relevanz und Effizienz, Positionierung und Gewichtung in Bezug auf Abgrenzung und Vernetzung,

- Differenzierung subjektiver und objektiver Daten, https://polizei.nrw/artikel/lagebild-jugendkriminalitaet-und-gefaehrdung[Internetidentität], https://www.ldi.nrw.de/mainmenu_Datenschutz/[Daten- und Persönlichkeitsschutz], Kommunikationsformen, Kompetenzförderung hinsichtlich formaler und technischer Anwendungen,

- Unterscheidung, Auswahl und Nutzung von Standardanwendungen (s. software), strukturiertes Lernen, sammeln, schützen, aufbereiten und präsentieren von Informationen,

- Unterscheidung und Bedeutung von (Software-) Lizenzen wie
https://de.wikipedia.org/wiki/Propriet%C3%A4r#Verschiedene_Bedeutungen[proprietär], https://www.gnu.org/licenses/license-list.en.html[frei] oder https://opensource.org/licenses[offen], und https://creativecommons.org/licenses/[urheberrechtlichen Jedermannlizenzen] hinsichtlich der eigenen Nutzung und hinsichtlich wirtschaftlicher und gesellschaftlicher Entwicklung von Organisationen und Gemeinschaften, 

- Unterscheidung von personenbezogenen und unpersönlichen Daten der eigenen Person und der Daten von Dritten, Nutzung von https://bitbucket.org/mawima/avtbh/commits[Revisionskontrolle zur Entwicklung und Fortschreibung von Aufgaben oder des Portfolios],

- auditive und visuelle Applizierung von just-in-time Translation mit dem Schwerpunkt Integration von Seiteneinsteigern,

- https://www.medienanstalt-nrw.de/zum-nachlesen/forschung/abgeschlossene-projekte/schriftenreihe-medienforschung/geschlechtersensible-medienkompetenzfoerderung.html[geschlechtersensible Medienkompetenzförderung],

- Kompetenzförderung im Sinne des KJFP NRW (s.u.), insbesondere Förderbereich II: Junge Menschen verstärkt an der Gestaltung der Gesellschaft beteiligen, Förderbereich III: Jugendförderung zukunftsfähig gestalten

- https://www.bmi.bund.de/DE/themen/sicherheit/kriminalitaetsbekaempfung-und-gefahrenabwehr/cyberkriminalitaet/cyberkriminalitaet-node.html[Cyberkriminalität],

- Rechtsgeschäfte im Internet,

== Curriculare Anbindung; geltende Erlasse:

http://www.berufsbildung.nrw.de/cms/bildungsgaenge-bildungsplaene/ausbildungsvorbereitung-anlage-a/bildungsplaene/index.html[Bildungspläne für das Berufskolleg in Nordrhein-Westfalen; Bildungsgänge der Ausbildungsvorbereitung],

https://recht.nrw.de/lmi/owa/br_bes_text?anw_nr=1&gld_nr=2&ugl_nr=2160&bes_id=38930&menu=1&sg=0&aufgehoben=N&keyword=kinder%20und%20jugendf%F6rderplan#det0[Kinder- und Jugendförderplan des Landes Nordrhein-Westfalen 2018-2022 Bekanntmachung des Ministeriums für Kinder, Familie, Flüchtlinge und Integration (08.05.2018)]

https://medienkompetenzrahmen.nrw/medienkompetenzrahmen-nrw/[Medienkompetenzrahmen-NRW]
